[project]
name = "micropython-assignment-template"
version = "1.0.0"
requires-python = ">=3.11"
dependencies = [
    "gatorgrade",
    "mypy>=1.19.1",
    "pytest",
    "mpremote",
    "mockro"
]

[tool.pytest.ini_options]
pythonpath = [
    "src"
]
testpaths = [
    "tests"
]
filterwarnings = [
    "ignore::pytest.PytestAssertRewriteWarning"
]

[tool.mypy]
mypy_path = ["src"]
ignore_missing_imports = true
